services:
  - type: web
    name: potential-club-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: --no-cache-dir -r requirements.txt || pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CARGO_NET_GIT_FETCH_WITH_CLI
        value: "true"
